### ISSUE TITLE
TypeError: Cannot read property 'emit' of null

### ISSUE THREAD

**Issue by bdougie** [kadirahq/storybook-addon-notes#40]
Hello, I am trying to setup notes via the addons but getting an error after following the setup instructions and curious to know if anyone has seen this in their project.

Any insight on this would be very helpful.

My error:
![screenshot 2016-10-13 14 33 00](https://cloud.githubusercontent.com/assets/5713670/19367856/fcd1ceec-9151-11e6-82bc-b872eaebe6e8.png)

``` bash
// legible error message
Cannot read property 'emit' of null
TypeError: Cannot read property 'emit' of null
    at WithNotes.render (webpack:///~/@kadira/storybook-addon-notes/dist/index.js:56:14)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (webpack:///~/react/lib/ReactCompositeComponent.js:832:34)
    at ReactCompositeComponentWrapper._renderValidatedComponent (webpack:///~/react/lib/ReactCompositeComponent.js:859:34)
    at ReactCompositeComponentWrapper.performInitialMount (webpack:///~/react/lib/ReactCompositeComponent.js:383:30)
    at ReactCompositeComponentWrapper.mountComponent (webpack:///~/react/lib/ReactCompositeComponent.js:262:21)
    at Object.mountComponent (webpack:///~/react/lib/ReactReconciler.js:47:35)
    at ReactDOMComponent.mountChildren (webpack:///~/react/lib/ReactMultiChild.js:242:44)
    at ReactDOMComponent._createInitialChildren (webpack:///~/react/lib/ReactDOMComponent.js:715:32)
    at ReactDOMComponent.mountComponent (webpack:///~/react/lib/ReactDOMComponent.js:531:12)
    at Object.mountComponent (webpack:///~/react/lib/ReactReconciler.js:47:35)
```

My implementation

``` js
// stories/Cards.js
storiesOf("Cards", module)
  .add("Card Basic", () => (

    <WithNotes notes={"This is a very simple Button and you can click on it."}>
      <CardBasic><div style={{height: 200}}></div></CardBasic>
    </WithNotes>

  ))
```

``` js
// .storybook/addon.js
import "@kadira/storybook/addons";
import "@kadira/storybook-addon-notes/register";
```

Thanks for putting this project together.

**Comment by arunoda** [comment]
Could you check you are using the [latest version](https://www.npmjs.com/package/@kadira/storybook) of Storybook?

**Comment by arunoda** [comment]
Is this is still there, I'd like to have a sample repo where we can reproduce this.

**Comment by bdougie** [comment]
So I installed this months ago and didn't realize there was this version. I will try that now. 

I am on v1.36.0

**Comment by arunoda** [comment]
@bdougie that's the issue I hope.
We need to have Storybook 2.x

**Comment by bdougie** [comment]
I actually have @kadira/storybook-addons installed, what is the difference between this is and getstorybook? Its not very clear.

**Comment by arunoda** [comment]
You are asking a few different things.
You don't need to install `@kadira/storybook-addons` this manually.

All you have to do is to update your `@kadira/storybook` to 2.x

`getstorybook` is our tool to help you to get started when creating projects: https://getstorybook.io/docs/basics/quick-start-guide

**Comment by bdougie** [comment]
Oh ok thanks, so I don't need getstorybook. I just uninstalled @kadira/storybook and reinstalled it to update and I am good to go now. 

I am very interested in helping this project out, where is the repo for the documentation? https://getstorybook.io/docs/addons/using-addons 

FYI, I am giving a few talks on this project in the near future.  

Thanks for the help.

**Comment by arunoda** [comment]
Thanks. 
Here's the repo: https://github.com/kadirahq/getstorybook.io

Exited about the talk. Let me know, if you need anything from us.
